baseURL = 'https://icesca.github.io/'
languageCode = 'en-us'
title = "Young's blog"
theme = 'hugo-book'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
# for themes/hugo-book
  BookSearch = false
  BookComments = false

# for raw html like <a...> in markdown file
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

